### ISSUE TITLE
New Google AMP check - Disable async loading by variable

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-css-optimization#31] opened 2018-06-25 17:11 UTC
Google introduced a new check to the AMP part of search console, resulting in all AMP pages of all my sites using O10N flagged invalid.

The check flagged

onload="this.rel='stylesheet';"><script data-o10n=

as user defined javascript which is not allowed.

As fas as I can see this results from the async loading option. 

The async loading filter function however triggers on single css and not on the site URI.

So far, it would be good to have a 

`define ('O10N_DISABLE_CSSASYNC', true|false);
`
to be able to disable ASYNC css loading and the respective script on AMP pages.

**Comment by optimalisatie** [comment] 2018-06-25 17:41
If it's about the onload handler on th stylesheet, it's the official W3C async CSS load method that uses [loadCSS](https://github.com/filamentgroup/loadCSS) as polyfill. You've manually enabled that option.

The preload option will always download stylesheets from the browser cache. When using loadCSS as a script loader together with localStorage cache the performance may be better. You can test the performance by enabling `O10N_DEBUG`.

![image](https://user-images.githubusercontent.com/8843669/41865176-a1c318f0-78ac-11e8-988a-89bc76d355e9.png)

> The standard markup pattern for loading files asynchronously is: <link rel="preload"> (W3C Spec). We recommend using this markup pattern to reference your non-critical CSS files.
> 
> ```html
> <link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.rel='stylesheet'">
> ```
> https://github.com/filamentgroup/loadCSS

We will add conditional JSON configuration in a future update so that you can define any settings conditionally using JSON. This would make it possible to enable/disable async CSS loading for AMP pages.

```php
# conditionally set config by key
\O10n\config('css.async.enabled', false);

# conditionally set config by multiple keys
\O10n\config(array(
    'css.async.enabled' => false
));

# conditionally set config by JSON array
\O10n\config(array(
    'css' => array(
        'async' => array(
            'enabled' => false
        )
    )
), true);

# input raw JSON config (string)
\O10n\config(file_get_contents('path/to/custom-conditional-config.json'));
```

**Comment by AlphaDE** [comment] 2018-06-25 17:48
Jan, no doubt that it is implemented properly for "normal" websites. And there it is working good.

But at least Google considers it breaking an AMP page. Google notified this morning by mail that new AMP error types have been added to the AMP checker and that my sites were affected by this check.

I'd like to keep as much optimization for AMP as possible.

**Comment by AlphaDE** [comment] 2018-06-27 18:12
After disabling async loading, Google still complains about

onload="this.rel='stylesheet';"><script data-o10n='

All my AMP sites have been discarded from Google index...

**Comment by AlphaDE** [comment] 2018-06-27 18:19
And btw. the font loader causes the same problem, after disabling CSS and FONTS optimization for AMP pages, the pages are accepted.

**Comment by optimalisatie** [comment] 2018-07-08 08:30
We currently do not have time to investigate the plugins for compatibility / usability with AMP. However, if you have an idea / suggestion what should change to make it work with AMP / your specific use case, we could review it and may be able to add in a update.

**Comment by optimalisatie** [comment] 2018-07-08 09:53
The conditional config option has been added in the latest update. Please let us know if this enables to resolve the AMP issues. 

Conditional config enables to disable async CSS for AMP or to fine tune the settings (e.g. do not use the W3C `onload` method).

**Comment by AlphaDE** [comment] 2018-07-08 16:53
Can I enable that one similar to the other ones via wp_config.php (so I trigger on /amp/ or /?amp) or how does this work?

**Comment by optimalisatie** [comment] 2018-07-08 18:09
You can add it in `functions.php` (in the theme directory) or use a WordPress hook:

```php
// conditional optimization JSON config
add_action('init', function () {

    if (is_amp_endpoint()) {

        # conditionally set config by multiple keys
        \O10n\config(array(
            'css.async.enabled' => false,
            'css.minify.enabled' => false
        ));

        # alternative, use a JSON config file
        \O10n\config(file_get_contents('path/to/custom-conditional-config.json'));
    }

}, 10, 0);
```

Since the WPO optimization plugins are 100% controlled by JSON, you can truly fine tune each individual setting conditionally using JSON. For optimization purposes it is a very powerful feature.

**Comment by AlphaDE** [comment] 2018-07-08 18:20
:( 
And every theme update deletes those modifications... which prevents me from automatically updating themes when not at home with access to my computer. Adding and fixing this on the small screen of a mobile for several Wordpress installations is not really an option.

**Comment by optimalisatie** [comment] 2018-07-08 18:52
Maybe it would be an option to create a child theme with just a modified `functions.php`. It should then be preserved.

> **WordPress Child Themes: the safest way to customize!**
>
> Don't lose your custom WordPress theme changes every time you update! Learn how to make child themes for WordPress!
> 
> http://webcraft.tools/wordpress-child-themes/

**Comment by AlphaDE** [comment] 2018-07-08 18:57
I know child themes... these are mostly customer instances where I want to avoid such significant modifications. With the optimzation plugins, I could help to improve the site performance "in the background". 

What about defining a configuration file in wp_config.php and loading it when initializing the plugins. That way, specific config options could be collected into one or more file and the if conditions match, a variable like

O10N_CONFIG

would be set with the full filename relative to the webspace.

On initialization, that variable would be checked, the config read and the variables used.

That would "just" need the processing of that variable and loading the file at O10N init.

**Comment by optimalisatie** [comment] 2018-07-08 21:43
You could look into creating a stealth custom optimization plugin, for example using the `mu-plugin` folder.

https://codex.wordpress.org/Must_Use_Plugins

The custom plugin could be very simple. It would simply add a WordPress action hook that conditionally applies optimization configuration.

In a more advanced concept you could store the optimization config in physical JSON files. This would make it possible to update the settings from a local editor (with auto upload) making it very efficient for fine tuning settings. An update would cost a second compared to using + saving a WordPress admin panel.

### Example 

Plugin: `mu-plugins/AlphaDE_Optimization.php`

```php
<?php
/**
 * Plugin Name: AlphaDE Optimization
 * Description: Custom optimization configuration.
 * Author:      AlphaDE
 * License:     GNU General Public License v3 or later
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 */

// security
if (!defined( 'ABSPATH' ) { die( 'Forbidden' ); }

// plugin path
define('CUSTOM_O10N_PLUGIN_PATH') = dirname(__FILE__);

// conditional optimization JSON config
add_action('init', function () {

	$config_dirs = array();

	// AMP pages
	if (is_amp_endpoint()) {

		$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/amp/';

	} else {

		// load global config for all pages
		$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/global/';

		if (is_page([1,5,19])) {
			$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/special-page/';
		} else if (is_page()) {
			$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/page/';
		} else if (is_single()) {
			$config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/post/';
		}

	}

	// walk config directories in defined order
	foreach ($config_dirs as $dir) {

		// read config directory
		$files = new \FilesystemIterator($dir, \FilesystemIterator::SKIP_DOTS);
		foreach ($files as $fileinfo) {

			// verify file
			if (!$fileinfo->isFile() || $fileinfo->getExtension() !== 'json') {
				continue;
			}

			// load config
			\O10n\config(file_get_contents($dir . $fileinfo->getFilename()));
		}
	}

}, 10, 0);
```

**Comment by AlphaDE** [comment] 2018-07-09 20:00
Thanks Jan! For first testing, I coded the O10N settings directly into the plugin. But although the debug log shows that the plugin is executed and the amp check is trigfgered, , O10N stays active.

At least here, the "is_amp_endpoint" resulted in errors in the log and did not work.

Do I use the O10N commands in a wrong way?

<?php
/**
 * Plugin Name: Optimization
 * Description: Custom optimization configuration.
 * Author:      AlphaDE
 * License:     GNU General Public License v3 or later
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 */

// security
defined( 'ABSPATH' ) or die( 'Cheatin&#8217; uh?' );

// add akxnet.deinit function to WP init
add_action('init', 'special_optimization_init', 10, 0);

// conditional optimization JSON config
function special_optimization_init() {

    // AMP pages
    if (in_array(substr($_SERVER["REQUEST_URI"],-5),array('/?amp','/amp/'))) {
        \O10n\disable(true, array('js', 'http2', 'css'));

        \O10n\config(array(
            'css.async.enabled' => false,
            'css.minify.enabled' => false
        ));

    } else {

        if (strpos($_SERVER["REQUEST_URI"],"/civicrm/?page=CiviCRM") !== false) {
            \O10n\disable();
            $config_dirs[] = CUSTOM_O10N_PLUGIN_PATH . '/CiviCRM/';
        }
    }
    return true;
}
?>

**Comment by optimalisatie** [comment] 2018-07-10 06:40
Could you please post the full code? You could use a Github Gist (others will be able to find it)

https://gist.github.com/

**Comment by AlphaDE** [comment] 2018-07-10 10:53
Jan, will do, but that was the full code...

**Comment by optimalisatie** [comment] 2018-07-10 19:48
`\O10n\disable();` will completely disable the plugin. 

`\O10n\disable(true, array('js', 'http2', 'css'));` will disable the CSS optimization plugin. There is no need to edit CSS optimization settings after disabling the plugin.

There is no need to define a optimization configuration directory as you are not loading JSON files.

Does the `\O10n\disable();` method fail to disable the plugin?

You could test the status using the following code:

```php
# test disabled state
if (\O10n\Core::get('env')->enabled()) {
    die('enabled');
} else {
    die('disabled');
}

# test disabled state of modules
if (\O10n\Core::get('env')->enabled(array('js', 'http2', 'css'))) {
    die('enabled');
} else {
    die('disabled');
}
```

**Comment by optimalisatie** [comment] 2018-07-11 10:18
There was a small bug (not really a functional bug, but which caused the strange results as displayed in the test). The disabled state is cached locally for best performance (the plugin is (designed to be) optimized to achieve the best possible PHP performance). 

The latest update will update the local cache when you update the disable state using the public `\O10n\disable();` method.

Could you please try the test again?

**Comment by AlphaDE** [comment] 2018-07-11 11:18
That solved the switched, but

`\O10n\disable(true, array('js', 'http2', 'css', 'fonts'));
`
does not show the same effect as 

```
    define('O10N_DISABLED_JS', true);
    define('O10N_DISABLED_CSS', true);
    define('O10N_DISABLED_HTTP2', true);
    define('O10N_DISABLED_FONTS', true);
```

in wp_config.php. With the disable-statement in the plugin, Google AMP validator reports the page invalid, where with the define statement, the page get's valid.

**Comment by optimalisatie** [comment] 2018-07-11 11:36
There was a small bug. Critical CSS was not disabled when using `\O10n\disable('css');` in the WordPress `init` action hook. The issue is fixed in the latest update.

Could you please share the exact error reported by Google AMP when you use `\O10n\disable(true, array('js', 'http2', 'css', 'fonts'));`?

**Comment by AlphaDE** [comment] 2018-07-11 17:20
I updated the CSS plugin and the page remains invalid:

```
Ungültiges CSS-Stylesheet
Das Attribut "href" im Tag "link rel=stylesheet for fonts" weist den ungültigen Wert "/wp-content/cache/o10n/css/0/1/A.12,3Acritical.css.pagespeed.cf.ZvqYdtHjRu.css" auf.
1 Problem
Zeile 1:66
<link data-o10n rel="stylesheet" href="/wp-content/cache/o10
```


`<link data-o10n rel="stylesheet" href="/wp-content/cache/o10n/css/0/1/A.12,3Acritical.css.pagespeed.cf.ZvqYdtHjRu.css"/><script data-o10n='[[ø],ø:4,[{"3":[{"27":[{"26":"Lato","14":{"16":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-700.woff2","15":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-700.woff"},"28":{"20":39,"21":30}},{"26":"Lato","14":{"16":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-regular.woff2","15":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-regular.woff"},"28":{"20":36,"21":30}},{"26":"Lato","14":{"16":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-700italic.woff2","15":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-700italic.woff"},"28":{"20":39,"21":31}},{"26":"Lato","14":{"16":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-italic.woff2","15":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-italic.woff"},"28":{"20":36,"21":31}}],"8":{"10":{"12":"lato-loading"}},"9":{"10":{"13":"lato-loading"}}}],"6":[21]}],[[]]]'>!function(){function aa(a,c,b){c||(c=l);return b?c.querySelectorAll(a):c.querySelector(a)}var m=window,l=m.document,ba=l.documentElement,ca=l.head||"head".getElementsByTagName(void 0)[0],URL=m.URL,navigator=m.navigator,da=l.addEventListener,u=l.currentScript||aa("script[data-o10n]",ca);
`
and

```
Vom Nutzer erstellter JavaScript-Code auf Seite gefunden
Benutzerdefiniertes JavaScript ist nicht zulässig.
1 Problem
Zeile 1:186
<script data-o10n='[[ø],ø:4,[{"3":[{"27":[{"26":"Lato","14"
```

`<script data-o10n='[[ø],ø:4,[{"3":[{"27":[{"26":"Lato","14":{"16":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-700.woff2","15":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-700.woff"},"28":{"20":39,"21":30}},{"26":"Lato","14":{"16":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-regular.woff2","15":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-regular.woff"},"28":{"20":36,"21":30}},{"26":"Lato","14":{"16":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-700italic.woff2","15":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-700italic.woff"},"28":{"20":39,"21":31}},{"26":"Lato","14":{"16":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-italic.woff2","15":"https:\/\/static.mydomain.de\/wp-content\/themes\/graphene-plus\/fonts\/lato-v14-latin-italic.woff"},"28":{"20":36,"21":31}}],"8":{"10":{"12":"lato-loading"}},"9":{"10":{"13":"lato-loading"}}}],"6":[21]}],[[]]]'>!function(){function aa(a,c,b){c||(c=l);return b?c.querySelectorAll(a):c.querySelector(a)}var m=window,l=m.document,ba=l.documentElement,ca=l.head||"head".getElementsByTagName(void 0)[0],URL=m.URL,navigator=m.navigator,da=l.addEventListener,u=l.currentScript||aa("script[data-o10n]",ca);
`

**Comment by optimalisatie** [comment] 2018-07-11 18:10
The complaint appears to be related to the `href` link target of the following HTML:

```html
<link data-o10n rel="stylesheet" href="/wp-content/cache/o10n/css/0/1/A.12,3Acritical.css.pagespeed.cf.ZvqYdtHjRu.css"/>
```

The optimization plugins do not create cache files with a name like `A.12,3Acritical.css.pagespeed.cf.ZvqYdtHjRu.css`. An other plugin (cloudflare or pagespeed related?) appears to have modified the URL.

A stylesheet link with the attribute `data-o10n` is only created by the Critical CSS controller, so it appears that the error is related to the bug that was fixed in `v0.0.84`.

https://github.com/o10n-x/wordpress-css-optimization/commit/0e215d85412c47f0bd902e67a2642e8b1c713cc2#diff-fa81feda8851e204b7cae43b9957e973

**Comment by optimalisatie** [comment] 2018-07-13 09:51
`\O10n\disable(array('css', 'fonts', 'http2'));` disabled only the first module. The bug has been fixed in `v0.0.85`.

**Comment by AlphaDE** [comment] 2018-07-13 11:14
That's great news :)

**Comment by AlphaDE** [comment] 2018-07-13 16:09
Now, disabling of the modules work.

I now tried to disable css.async.enabled and css.minify.enabled to false instead of disabling the whole CSS module.

That AMP page again did not pass the test:

Invalid CSS stylesheet

`
<link data-o10n rel="stylesheet" href="/wp-content/cache/o10n/css/0/1/15:critical.css"/><script data-o10n='[[ø]]'>!function(){function aa(a,c,b){c||(c=l);return b?c.querySelectorAll(a):c.querySelector(a)}var m=window,l=m.document,ba=l.documentElement,ca=l.head||"head".getElementsByTagName(void 0)[0],URL=m.URL,navigator=m.navigator,da=l.addEventListener,v=l.currentScript||aa("script[data-o10n]",ca);`

and

User generated Java script found
`
<script data-o10n='[[ø]]'>!function(){function aa(a,c,b){c||(c=l);return b?c.querySelectorAll(a):c.querySelector(a)}var m=window,l=m.document,ba=l.documentElement,ca=l.head||"head".getElementsByTagName(void 0)[0],URL=m.URL,navigator=m.navigator,da=l.addEventListener,v=l.currentScript||aa("script[data-o10n]",ca);`

**Comment by optimalisatie** [comment] 2018-09-21 06:00
@AlphaDE 

You were using a file based critical CSS reference. Did you try to use the `<style>` version for AMP?

I am closing this topic as the original issue was resolved.

**Closed by optimalisatie** 2018-09-21 06:00 UTC
